### ISSUE TITLE
Fall Damage Modifier not handling culture well

### ISSUE THREAD

**Issue by WaldoAndFriends** [PhantomBadger/JumpKing-TwitchRavens#5]
I was planning on streaming Jump King with the fall damage mod.
However, by default the fall damage was set to `5` resulting in instant death. I figured this wasn't the intended behavior so I checked the docs and saw a screenshot with the value `0.05`.

I suspect the code doesn't handle the user's culture well.
I'm from the Netherlands so we use a `,` as a separator instead of a `.`. This also results in me not being able to enter `0.05` via the numpad. However, I am able to enter `0,05` manually, but upon loading the settings this changes back to `5`.

Fixed it temporarilly by setting the value in `JumpKingModifiersMod.settings` myself:
```json
    "FallDamageModifier": "0.05",
```

**Comment by PhantomBadger** [comment]
Ah thank you! I'd caught the culture issue when loading the settings but not when writing them out from the installer - apologies for the inconvenience! I'll get a fix together in the next day or so :)

**Comment by PhantomBadger** [comment]
Fixed in submit 5cd4c2aa28707100a2c031867ee60412fb093951
I'll prep a minor release when I get a sec

**Comment by PhantomBadger** [comment]
Following testing with Waldo, additional fix submitted in 2e76fd7c17170131655ff1d1f4f52658e15b3120

Fixed in [Release v4.1a](https://github.com/PhantomBadger/JumpKing-TwitchRavens/releases/tag/v4.1a)
