### ISSUE TITLE
Jump charge time different from the base game

### ISSUE THREAD

**Issue by Jakomo23** [PhantomBadger/JumpKing-TwitchRavens#7]
I just set up the settings for the chaos mod and tested it out and it worked fine except I failed every jump. So I wanted to test if its me or something is wrong with the charge time. After repairing my files it was fine again. 
I checked the frames for the full jump charge up with JK+. For the base game its 35 frames and for the game with the mod its 21 frames.
Idk if I am the only person with this problem or if I could fix it manually.

**Comment by PhantomBadger** [comment]
Hey Jakomo!
That's an odd one for sure, there is a Quicker Jump Time modifier you can enable but presumably this is happening without that being active? I don't mess with the Jump system outside of that modifier or the Bouncy one (which doesn't affect the charge time).
I won't have access to a computer until later today to verify but I can't spot anything from a quick look at the code on my phone. I'll try and do some measuring tonight and see what I can find! 
Sorry for the issues!

**Comment by PhantomBadger** [comment]
Just got some times myself that appear similar to your own - I don't have the best way to measure them but I was getting this pretty consistently from my clips recorded at 60FPS and stepped through in Shotcut:

Base game - 38 frames
Mod - 23 frames

It looks like in one of my patches I apply a modifier to the Jump Charge time, but I set the default value to 0.6 (which is the _actual_ value the jump should be, _not_ the modifier to be applied to it)

I'll get a fix prepped now, thank you for finding this, sorry it happened!

**Comment by PhantomBadger** [comment]
Fix submitted in f01a4b275be86e0f6116deb643a7be10ec720a6b

**Comment by PhantomBadger** [comment]
Fixed in https://github.com/PhantomBadger/JumpKing-TwitchRavens/releases/tag/v5.1
